config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/country.rb
class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'アルジェリア' },
    { id: 3, name: 'アンゴラ' },
    { id: 4, name: 'ウガンダ' },
    { id: 5, name: 'エジプト' },
    { id: 6, name: 'エスワティニ' },
    { id: 7, name: 'エチオピア' },
    { id: 8, name: 'エリトリア' },
    { id: 9, name: 'ガーナ' },
    { id: 10, name: 'カーボベルデ' },
    { id: 11, name: 'ガボン' },
    { id: 12, name: 'カメルーン' },
    { id: 13, name: 'ガンビア' },
    { id: 14, name: 'ギニア' },
    { id: 15, name: 'ギニアビサウ' },
    { id: 16, name: 'ケニア' },
    { id: 17, name: 'コートジボワール' },
    { id: 18, name: 'コモロ' },
    { id: 19, name: 'コンゴ共和国' },
    { id: 20, name: 'コンゴ民主共和国' },
    { id: 21, name: 'サントメ・プリンシペ' },
    { id: 22, name: 'ザンビア' },
    { id: 23, name: 'シエラレオネ' },
    { id: 24, name: 'ジブチ' },
    { id: 25, name: 'ジンバブエ' },
    { id: 26, name: 'スーダン' },
    { id: 27, name: 'セーシェル' },
    { id: 28, name: '赤道ギニア' },
    { id: 29, name: 'セネガル' },
    { id: 30, name: 'ソマリア' },
    { id: 31, name: 'タンザニア' },
    { id: 32, name: 'チャド' },
    { id: 33, name: '中央アフリカ' },
    { id: 34, name: 'チュニジア' },
    { id: 35, name: 'トーゴ' },
    { id: 36, name: 'ナイジェリア' },
    { id: 37, name: 'ナミビア' },
    { id: 38, name: 'ニジェール' },
    { id: 39, name: 'ブルキナファソ' },
    { id: 40, name: 'ブルンジ' },
    { id: 41, name: 'ベナン' },
    { id: 42, name: 'ボツワナ' },
    { id: 43, name: 'マダガスカル' },
    { id: 44, name: 'マラウイ' },
    { id: 45, name: 'マリ' },
    { id: 46, name: '南アフリカ' },
    { id: 47, name: '南スーダン' },
    { id: 48, name: 'モザンビーク' },
    { id: 49, name: 'モーリシャス' },
    { id: 50, name: 'モーリタニア' },
    { id: 51, name: 'モロッコ' },
    { id: 52, name: 'リビア' },
    { id: 53, name: 'リベリア' },
    { id: 54, name: 'ルワンダ' },
    { id: 55, name: 'レソト' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '人々' },
    { id: 3, name: '食事' },
    { id: 4, name: '暮らし' },
    { id: 5, name: 'ファッション' },
    { id: 6, name: 'スポーツ' },
    { id: 7, name: '文化' },
    { id: 8, name: '観光' },
    { id: 9, name: 'ビジネス' },
    { id: 10, name: '教育' },
    { id: 11, name: '歴史' },
    { id: 12, name: '経済' },
    { id: 13, name: '宗教' },
    { id: 14, name: '小ネタ' },
    { id: 15, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :country
  belongs_to :genre

  with_options presence: true do
    validates :title, length: { maximum: 40}   
    validates :text
    validates :image
  end   
  
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :country_id
    validates :genre_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :nickname, presence: true, length: { maximum: 20}   
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts       
  has_many :comments
 
  
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数字混合で入力してください' 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      @comments = @post.comments
      render "posts/show" 
    end  
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_post, only: [:show, :edit, :update]
  before_action :move_to_index, except: [:index, :show, :new, :create, :destroy, :search]
  before_action :search_post, only: [:index, :search]

  def index  
    @posts = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def new 
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end  
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit    
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(params[:id])
    else
      render :edit    
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def search
    @results = @p.result.order("created_at DESC").page(params[:page]).per(5)
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :text, :country_id, :genre_id, :image).merge(user_id: current_user.id)  
  end  

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @post.user_id
      redirect_to action: :index
    end
  end

  def search_post
    @p = Post.ransack(params[:q])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show  
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MottoAfrica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("motto-africa-logo.png", class: :logo), root_path%>
          </div> 
          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to current_user.nickname, "/users/#{current_user.id}", class: "nav__nickname" %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav__logout"%>
            </div>    
          <% else %> 
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: "nav__btn"%>
              <%= link_to "新規登録", new_user_registration_path, class: "nav__btn"%>
            </div>
          <% end %>   
        </div>
      </div>
    </header>        
    <%= yield %>
    <footer class="footer">
      <p class="copyright">©️ 2020 Motto Africa</p>
    </footer>  
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f|%>

<%= render 'shared/error_messages', model: f.object %>
  
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :text, "内容" %><br />
    <%= f.text_area :text, rows: "10", class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :country_id, "国名" %><br />
    <%= f.collection_select(:country_id, Country.all, :id, :name, {}, {class:"select-box"}) %>
  </div>

    <div class="field">
    <%= f.label :genre_id, "ジャンル" %><br />
    <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box"}) %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
       <div class='article-lists'> 
        <div class='article-one'>
          <%= image_tag post.image, class: "article-img"%>
          <div class="article-info">
            <div class="article-title">
              <%= post.title %>
            </div>
            <div class="article-info-group1">  
              <div class="article-country">
                <%= post.country.name %>
              </div>
              <div class="article-genre">
                <%= post.genre.name %>
              </div>
              <div class="article-date">
                <%= l post.created_at %>
              </div>  
             </div> 
            <div class="article-info-group2">  
              <%= image_tag 'icon-user.png', class: "article-icon" %>
              <div class="article-user">
              <%= post.user.nickname %>
              </div>
            </div> 
             <div class="article-details">
              <%= link_to "記事を読む", post_path(post.id) %>
             </div>
          </div>  
        </div>
      </div>

app/views/posts/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿内容の編集</h2>
      <%= render partial: "form", locals: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<main class="main">
    <div class='title-contents'>
      <div class='bg-opacity'>
        <h2 class='service-title'>
          アフリカをもっと身近に感じられるアプリ
        </h2>
        <p class='service-explain'>
          Motto Africaはアフリカに関する記事を投稿して
        </p>
        <p class='service-explain'>
          様々な情報を共有できるアプリです
        </p>
      </div>
    </div>
    
    <div class="search-contents">
      <h1 class="search-title">記事検索</h1>
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.label :country_id_eq, '国名', class: "search-name" %>
        <%= f.collection_select :country_id_eq, Country.where.not(id: 1), :id, :name, include_blank: '指定なし' %>
        <br>
        <%= f.label :genre_id_eq, 'ジャンル', class: "search-name" %>
        <%= f.collection_select :genre_id_eq, Genre.where.not(id: 1), :id, :name, include_blank: '指定なし' %>
        <br>
        <%= f.submit '検索', class: "search-btn" %>
      <% end %>
    </div>  

    <div class="article-contents">
      <h1>投稿された記事一覧</h1>
      <div class='article-lists'>
        <% @posts.each do |post| %>
        <div class='article-one'>
          <%= image_tag post.image, class: "article-img"%>
          <div class="article-info">
            <div class="article-title">
              <%= post.title %>
            </div>
            <div class="article-info-group1">  
              <div class="article-country">
                <%= post.country.name %>
              </div>
              <div class="article-genre">
                <%= post.genre.name %>
              </div>
              <div class="article-date">
                <%= l post.created_at %>
              </div>  
             </div> 
            <div class="article-info-group2">  
              <%= image_tag 'icon-user.png', class: "article-icon" %>
              <div class="article-user">
              <%= post.user.nickname %>
              </div>
            </div>
             <div class="article-details">
              <%= link_to "記事を読む", post_path(post.id) %>
             </div>
          </div>  
        </div>
        <% end %>
      </div>  
      <%= paginate @posts %>  
    </div>    

  <%= link_to(new_post_path, class: 'article-btn') do %>
    <span class='article-btn-text'>投稿する</span>
    <%= image_tag 'icon-africa.png',class: "article-btn-icon" %>
  <% end %>
</main>    

app/views/posts/new.html.erb
<div class="main">
  <div class="inner-other">
    <h2 class="page-heading">新規投稿</h2>
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/search.html.erb
<main class="main">
  <% if @results.length !=0 %>
  <div class="search-contents">
    <h1>
      記事検索
    </h1>
      <%= search_form_for @p, url: search_posts_path do |f| %>
        <%= f.label :country_id_eq, '国名' %>
        <%= f.collection_select :country_id_eq, Country.where.not(id: 1), :id, :name, include_blank: '指定なし' %>
        <br>
        <%= f.label :genre_id_eq, 'ジャンル' %>
        <%= f.collection_select :genre_id_eq, Genre.where.not(id: 1), :id, :name, include_blank: '指定なし' %>
        <br>
        <%= f.submit '検索', class: "search-btn" %>
      <% end %>
    </div> 
    
    <div class="article-contents">
      <h1>検索結果</h1>
      <div class='article-lists'>
        <% @results.each do |result| %>
        <div class='article-one'>
          <%= image_tag result.image, class: "article-img"%>
          <div class="article-info">
            <div class="article-title">
              <%= result.title %>
            </div>
            <div class="article-info-group1">  
              <div class="article-country">
                <%= result.country.name %>
              </div>
              <div class="article-genre">
                <%= result.genre.name %>
              </div>
              <div class="article-date">
                <%= l result.created_at %>
              </div>  
            </div> 
            <div class="article-info-group2">  
              <%= image_tag 'icon-user.png', class: "article-icon" %>
              <%= link_to result.user.nickname, "/users/#{result.user.id}", class: "article-user" %>
            </div> 
            <div class="article-details">
              <%= link_to "記事を読む", post_path(result.id) %>
            </div>
          </div>  
        </div>
        <% end %>
      </div>  
      <%= paginate @results %>
      <%= link_to 'トップページへ戻る', root_path, class: "return-btn"  %>  
    </div>    

  <%= link_to(new_post_path, class: 'article-btn') do %>
    <span class='article-btn-text'>投稿する</span>
    <%= image_tag 'icon-africa.png',class: "article-btn-icon" %>
  <% end %>
</main>

    <% else %>
    <div class="article-contents">
      <h1 class="title">検索結果</h1>
      <br>
      <h2>  該当する記事はありません</h2> 
      <br>
      <%= link_to 'トップページへ戻る', root_path, class: "return-btn"  %>        
    </div> 

  <%= link_to(new_post_path, class: 'article-btn') do %>
    <span class='article-btn-text'>投稿する</span>
    <%= image_tag 'icon-africa.png',class: "article-btn-icon" %>
  <% end %>
    <% end %>
</main>

app/views/posts/show.html.erb
<main class="main">
  <div class="inner">
    <div class="article-contents">
      <div class='article-lists'>
        <div class='article-one'>
          <%= image_tag @post.image, class: "article-img"%>
          <div class="article-info">    
            <div class="article-title">
              <%= @post.title %>
            </div>
            <div class="article-info-group1">  
              <div class="article-country">
                <%= @post.country.name %>
              </div>
              <div class="article-genre">
                <%= @post.genre.name %>
              </div>
              <div class="article-date">
                <%= l @post.created_at %>
              </div>  
            </div> 
            <div class="article-info-group2">  
              <%= image_tag 'icon-user.png', class: "article-icon" %>
              <div class="article-user">
              <%= @post.user.nickname %>
            </div>
          </div>
        </div>
      </div>
      <div class='article-text'>
        <%= safe_join(@post.text.split("\n"),tag(:br)) %>
      </div>
    </div> 
        
    <%= link_to "#{@post.user.nickname}さんの投稿した記事の一覧へ", "/users/#{@post.user_id}", class: :post__user %>  
    
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="post__manage">
        <%= link_to "編集", edit_post_path(@post.id), class: :post__btn %>
        <%= link_to "削除", post_path(@post.id), method: :delete, class: :post__btn %>
      </div>
    <% end %> 

    <div class="post__comments">
      <% if user_signed_in? %>
        <%= form_with(model: [@post, @comment], local: true) do |f|%>
          <div class="field">
            <%= f.label :text, "コメント" %><br />
            <%= f.text_field :text %>
          </div>
          <div class="actions">
            <%= f.submit "送信する", class: :form__btn  %>
          </div>
        <% end%>
      <% end%>
      <ul class="comments_lists">
      <% @comments.each do |comment| %>
        <li class="comments_list">
          <p>
            <%= comment.text%>
            <%= link_to "(#{comment.user.nickname})", "/users/#{comment.user_id}", class: :comment_user %>
          </p>  
        </li>
      <% end %>
      </ul>  
    </div>  
  </div> 
</main>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="article-contents">
    <h1 class="user-posts">
      <%= "#{@user.nickname}さんの投稿"%>
    </h1>
  <%= render partial: "posts/post", collection: @posts %>
    <%= paginate @posts %>  
  </div>
</div>